require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - gemfiles/*.gemfile

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/BlockLength:
  Exclude:
    - factory_manager.gemspec
    - spec/**/*_spec.rb

Naming/RescuedExceptionsVariableName:
  PreferredName: error

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/ExampleLength:
  Max: 20

RSpec/FilePath:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true
  RequireForNonPublicMethods: true

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%w": "()"

Style/RaiseArgs:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes
