name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"

    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Run the tests and lint the code
        env:
          COVERAGE: true
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec appraisal install
          bundle exec appraisal rake check
